[package]
name = "my_kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "=0.9.31"
# bootloader_api = "0.9.8"
x86_64 = "=0.14.12"
linked_list_allocator = "=0.10.5"
spin = "=0.9.0"
embedded-sdmmc = { version = "=0.5.0", default-features = false }
waker-fn = "=1.1.0"
