# One should also update osdk/src/commands/new/rust-toolchain.toml.template
# when updating this
[toolchain]
channel = "nightly-2024-11-08"
components = ["rust-src", "rustc-dev", "llvm-tools-preview"]
targets = ["x86_64-unknown-none"]
